### ISSUE TITLE
How can I realize the feature transfer which is introduced in the paper.

### ISSUE THREAD

**Issue by Revive624** [schardong/ifmorph#5]
Dear authors:
The excellent work has made a great improvement on image warping. However, I'm still confusing about feature transfer which is introduced just a little in the paper. How can I achieve feature transfer between 2 persons using the code?
Thank you.

**Comment by schardong** [comment]
Hello, Revive624. Thank you very much!

The feature transfer is not as straightforward, since it involves the image warping followed by a **localized blending**. Unfortunately there wasn't a lot of space to explain the process in the paper.

Basically, you start with a warping of the two images. The warping must be very accurate around the region you wish to transfer, so I would suggest marking more points for warping there. This is done using the `mark-warp-points.py` and `warp-train.py` scripts.

With the warping trained, you can use the `poisson-blending.py` script to make a localized blending. Note that it is still very basic. I've just created the commit f9c6986 fixing some issues I found on `poisson-blending.py`

The gist is:
1. Create a warping between the images you want
2. Create a configuration file for the blending (see the template at `experiments/poisson.yaml`)
3. Run the `poisson-blending.py` script: `python poisson-blending.py experiments/YOUR-BLENDING-CONFIG.yaml -o results/your-blending`
4. The landmark editing UI should open, mark define the region on the **left** image (the one not blacked out)
5. Wait for the training to complete. Periodic reconstructions and checkpoints will be saved in the output directory you chose on step 3

 Note that the image shown in the UI on step 4 is a blending of the two images you warped. This helped us assess the warping quality and mark the blending region. If you wish, you can change this directly in the `poisson-blending.py` source code.

I hope this helps! If you have any questions, just reopen the issue, We'll be glad to help.

**Comment by schardong** [comment]
BTW, I'll add something to the README regarding this.
